/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MENU;

import JUEGO.BOARD;
import USUARIO.ManagerUsuarios;
import USUARIO.Usuario;
import java.awt.Component;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Josue Gavidia
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    ManagerUsuarios managerUsers;

    public MenuPrincipal() {

        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        this.REG_TAB.setVisible(false);
        this.PLAY_TAB.setVisible(false);
        this.MAIN_MENU.setVisible(false);
        

        try {
            managerUsers = new ManagerUsuarios();
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        } catch (ClassNotFoundException e) {

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MAIN_MENU = new javax.swing.JPanel();
        PLAY = new javax.swing.JButton();
        REG_TAB = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        us = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        fullName = new javax.swing.JTextField();
        Reg_Checkout = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        confPass = new javax.swing.JTextField();
        PLAY_TAB = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        us1 = new javax.swing.JTextField();
        pass1 = new javax.swing.JTextField();
        fullName1 = new javax.swing.JTextField();
        Reg_Checkout1 = new javax.swing.JButton();
        LOG_IN = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        usLogin = new javax.swing.JTextField();
        passLogin = new javax.swing.JTextField();
        checkOut = new javax.swing.JButton();
        reg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1920, 1080));

        MAIN_MENU.setBackground(new java.awt.Color(51, 0, 0));
        MAIN_MENU.setPreferredSize(new java.awt.Dimension(1920, 1080));
        MAIN_MENU.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PLAY.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        PLAY.setText("JUGAR");
        PLAY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLAYActionPerformed(evt);
            }
        });
        MAIN_MENU.add(PLAY, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 460, 330, 90));

        REG_TAB.setBackground(new java.awt.Color(51, 0, 0));
        REG_TAB.setPreferredSize(new java.awt.Dimension(1920, 1080));
        REG_TAB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        jLabel1.setText("NOMBRE COMPLETO");
        REG_TAB.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 350, 100));

        jLabel2.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        jLabel2.setText("USUARIO");
        REG_TAB.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 230, 100));

        jLabel3.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        jLabel3.setText("CONTRASEñA");
        REG_TAB.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 230, 100));

        us.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        us.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        REG_TAB.add(us, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 420, 550, 80));

        pass.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        pass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        REG_TAB.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, 550, 80));

        fullName.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        fullName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        REG_TAB.add(fullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 300, 550, 80));

        Reg_Checkout.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        Reg_Checkout.setText("REGISTRARSE");
        Reg_Checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reg_CheckoutActionPerformed(evt);
            }
        });
        REG_TAB.add(Reg_Checkout, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 780, 330, 90));

        jLabel7.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        jLabel7.setText("CONFIRMAR CONTRASEñA");
        REG_TAB.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 640, 430, 100));

        confPass.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        confPass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        REG_TAB.add(confPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 650, 550, 80));

        PLAY_TAB.setBackground(new java.awt.Color(51, 0, 0));
        PLAY_TAB.setPreferredSize(new java.awt.Dimension(1920, 1080));
        PLAY_TAB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        jLabel4.setText("NOMBRE COMPLETO");
        PLAY_TAB.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 350, 100));

        jLabel5.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        jLabel5.setText("USUARIO");
        PLAY_TAB.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 230, 100));

        jLabel6.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        jLabel6.setText("CONTRASEñA");
        PLAY_TAB.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 230, 100));

        us1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        us1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PLAY_TAB.add(us1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 430, 550, 80));

        pass1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        pass1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PLAY_TAB.add(pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, 550, 80));

        fullName1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        fullName1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PLAY_TAB.add(fullName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 300, 550, 80));

        Reg_Checkout1.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        Reg_Checkout1.setText("REGISTRARSE");
        PLAY_TAB.add(Reg_Checkout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 690, 330, 90));

        LOG_IN.setBackground(new java.awt.Color(51, 0, 0));
        LOG_IN.setPreferredSize(new java.awt.Dimension(1920, 1080));
        LOG_IN.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        jLabel9.setText("USUARIO");
        LOG_IN.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 230, 100));

        jLabel10.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        jLabel10.setText("CONTRASEñA");
        LOG_IN.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 230, 100));

        usLogin.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        usLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LOG_IN.add(usLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 420, 550, 80));

        passLogin.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        passLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LOG_IN.add(passLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, 550, 80));

        checkOut.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        checkOut.setText("INICIAR SESION");
        checkOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutActionPerformed(evt);
            }
        });
        LOG_IN.add(checkOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 690, 330, 90));

        reg.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        reg.setText("REGISTRARME");
        reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regActionPerformed(evt);
            }
        });
        LOG_IN.add(reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 690, 310, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MAIN_MENU, javax.swing.GroupLayout.DEFAULT_SIZE, 1932, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(REG_TAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PLAY_TAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 6, Short.MAX_VALUE)
                    .addComponent(LOG_IN, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MAIN_MENU, javax.swing.GroupLayout.DEFAULT_SIZE, 1092, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(REG_TAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PLAY_TAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 6, Short.MAX_VALUE)
                    .addComponent(LOG_IN, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PLAYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLAYActionPerformed
        this.PLAY_TAB.setVisible(true);
        this.MAIN_MENU.setVisible(false);
        this.setVisible(false);
        BOARD game = new BOARD();
        game.setVisible(true);

    }//GEN-LAST:event_PLAYActionPerformed

    private void Reg_CheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reg_CheckoutActionPerformed
        try {
            String name, user, pw;
            name = this.fullName.getText();
            user = this.us.getText();
            pw = this.pass.getText();
            if (name != null && user != null && pw != null && confPass != null) {
                if (managerUsers.SearchUser(user) == null) {
                    if (!confPass.getText().equals(pass.getText())) {
                        JOptionPane.showMessageDialog(null, "LAS CONTRASEñA NO COINCIDE");
                        return;
                    }
                    managerUsers.Serializer(new Usuario(name, user, pw));
                    JOptionPane.showMessageDialog(null, "USUARIO REGISTRADO");
                    System.out.println(managerUsers.SearchUser(user).getNAME() + " Has been Registered");

                    //Limpieza de textFields
                    for (Component a : this.REG_TAB.getComponents()) {

                        if (a instanceof JTextField) {

                            JTextField text = (JTextField) a;
                            text.setText(null);
                        }

                    }
                    this.REG_TAB.setVisible(false);
                    this.LOG_IN.setVisible(true);
                   

                } else {
                    JOptionPane.showMessageDialog(null, "NOMBRE DE USUARIO EN USO");
                }

            } else {
                JOptionPane.showMessageDialog(null, "LLENE TODOS LOS CAMPOS");
            }
        } catch (IOException | ClassNotFoundException e) {
            System.out.println(e.getMessage());
        }


    }//GEN-LAST:event_Reg_CheckoutActionPerformed

    private void checkOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutActionPerformed
        String user, pw;
       
        user = this.usLogin.getText();
        pw = this.passLogin.getText();
      try{ 
        if (user!= null && pw != null){
            Usuario temp = managerUsers.SearchUser(user);
            if(user.equals(temp.getUsername())&&pw.equals(temp.getPassword())){
                JOptionPane.showMessageDialog(null, "Bienvenido "+temp.getNAME()+" ^ - ^");
                
                //Limpieza
                 for (Component a : this.LOG_IN.getComponents()) {

                        if (a instanceof JTextField) {

                             ((JTextField) a).setText(null);
                            
                        }

                    }
                 this.LOG_IN.setVisible(false);
                 this.MAIN_MENU.setVisible(true);
                 
                
            }else{
                JOptionPane.showMessageDialog(null, "USUARIO O CONTRASEñA INCORRECTO");
            }
        }else  JOptionPane.showMessageDialog(null, "LLENE TODOS LOS CAMPOS");
      }catch(IOException | ClassNotFoundException e){
          System.out.println(e.getMessage());
      }
    }//GEN-LAST:event_checkOutActionPerformed

    private void regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regActionPerformed
        this.LOG_IN.setVisible(false);
        this.REG_TAB.setVisible(true);

    }//GEN-LAST:event_regActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LOG_IN;
    private javax.swing.JPanel MAIN_MENU;
    private javax.swing.JButton PLAY;
    private javax.swing.JPanel PLAY_TAB;
    private javax.swing.JPanel REG_TAB;
    private javax.swing.JButton Reg_Checkout;
    private javax.swing.JButton Reg_Checkout1;
    private javax.swing.JButton checkOut;
    private javax.swing.JTextField confPass;
    private javax.swing.JTextField fullName;
    private javax.swing.JTextField fullName1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField pass1;
    private javax.swing.JTextField passLogin;
    private javax.swing.JButton reg;
    private javax.swing.JTextField us;
    private javax.swing.JTextField us1;
    private javax.swing.JTextField usLogin;
    // End of variables declaration//GEN-END:variables
}
